using AdventOfCode2022.Days;
using static System.Console;

WriteLine("+ * = * + = * = +| Advent of Code 2022 |+ = * = + * = * +");
//WriteLine("                 =>+-+>   Day 1   <+-+<=                 ");
//WriteLine("        >-=>>+-+>   Calorie Counting   <+-+<<=-<         ");
//WriteLine($"+> Part 1: The elf carrying the most calories carries {Day1Part1.Run()} calories");
//WriteLine($"+> Part 2: The first 3 elves with the most calories are carrying {Day1Part2.Run()} calories");
//WriteLine("                 =>+-+>   Day 2   <+-+<=                 ");
//WriteLine("       >-=>>+-+>   Rock Paper Scissors   <+-+<<=-<       ");
//WriteLine($"+> Part 1: By following the strategy guide, the score will be {Day2Part1.Run()}");
//WriteLine($"+> Part 2: With the whole explanation, the score will be {Day2Part2.Run()}");
//WriteLine("                 =>+-+>   Day 3   <+-+<=                 ");
//WriteLine("     >-=>>+-+>   Rucksack Reorganization   <+-+<<=-<     ");
//WriteLine($"+> Part 1: The sum of the priorities of those item types is {Day3Part1.Run()}");
//WriteLine($"+> Part 2: The sum of the priorities of those item types is {Day3Part2.Run()}");
//WriteLine("                 =>+-+>   Day 4   <+-+<=                 ");
//WriteLine("           >-=>>+-+>   Camp Cleanup   <+-+<<=-<          ");
//WriteLine($"+> Part 1: One range fully contains the other in {Day4Part1.Run()} pairs");
//WriteLine($"+> Part 2: The ranges overlap in {Day4Part2.Run()} pairs");
WriteLine("                 =>+-+>   Day 5   <+-+<=                 ");
WriteLine("          >-=>>+-+>   Supply Stacks   <+-+<<=-<          ");
WriteLine($"+> Part 1: The crates ending on top of each stacks are {Day5Part1.Run()}");
WriteLine($"+> Part 2: The crates ending on top of each stacks are {Day5Part2.Run()}");